### PR TITLE
Added Implementation of Count Occurence of an Element in Array Functions

### PR DESCRIPTION
**Pull request by Subhoshri**
## Method of Implementation
- Created Dictionary/Unordered_Map/HashMap in respective languages to calculate the frequency of each element
- Returned count of the desired element
- All functions have been completed in O(N) Time Complexity and O(N) Space Complexity

## Tasks Completed
- [x] Added the files count_occurence.py, count_occurence.java and count_occurence.cpp in the corresponding directory
- [x] My code aligns with the specified structure.
- [x] Updated [RoadMap.md](https://github.com/imsuraj675/CodeStock/blob/main/RoadMap.md)

### CODE REVIEW

**Comment by imsuraj675** [comment]
I guess I have written wrong in the RoadMap.md. It should be Count occurrence of every element. So instead of returning the count of desired element, return the map. Also modify the function in RoadMap.md. Change it to "Count occurrences of element"

**Comment by Subhoshri** [comment]
Okay, will do that

**Comment by imsuraj675** [comment]
Your modifications have some conflicts. Make sure to resolve it first by executing **git pull** first. To temporary store your modification, use **git stash** and **git stash apply** commands

**Comment by Subhoshri** [comment]
I have made the changes mentioned and resolved any conflict that was occurring.

**Comment by imsuraj675** [comment]
Good work

**Pull request merged**
