### PR TITLE
Added palindrome check function for Strings

### PR DESCRIPTION
**Pull request by KakarotDB**
## Description
Checking for palindrome string. 
Created a two functions, "reverse" and "check_for_palindrome" along with test cases given in the "main" method

## Tasks completed
- [x] Added the files palindrome_Check.java, palindrome_Check.cpp, and palindrome_check.py in the corresponding directory.
- [x] Updated [Roadmap.md](Roadmap.md)

### CODE REVIEW

**Comment by imsuraj675** [comment]
Don't raise a PR until and unless you are assigned to an issue.

**Comment by imsuraj675** [comment]
Don't reverse the string just to check for palindrome. Instead just use Two pointers to do this, this would not only reduce space complexity but also time complexity.

**Comment by KakarotDB** [comment]
Okay

**Comment by KakarotDB** [comment]
I have updated the pull request, kindly review the changes

**Comment by imsuraj675** [comment]
Good work

**Comment by KakarotDB** [comment]
thank you

**Pull request merged**
