### PR TITLE
Added implementation for Generate all subsequences of string in Java, C++, and Python

### LINKED ISSUE #2: [Add] String Algorithms: Generate all Substrings (2^n)
Add a function to generate all substrings (sub-sequences) in the structure as described in [Contribution.md](../blob/main/Contribution.md).
Give a small proposal describing your method of implementation.

Checklist:
- [ ] Added the files gen_substr.py, gen_substr.java and gen_substr.cpp in the corresponding directory
- [ ] My code aligns with the specified structure.
- [ ] Updated [RoadMap.md](../blob/main/RoadMap.md)

### PR DESCRIPTION
**Pull request by ittou-shura**
### Summary
Added the implementation for **Generate All Subsequences** in three programming languages (Java, C++, Python) and updated the `RoadMap.md` file.

### Issue Link
Fixes #2 https://github.com/imsuraj675/CodeStock/issues/2.

### Changes Made
1. Created a new folder `generate_all_subsequences/` containing:
   - `gen_subseq.java`
   - `gen_subseq.cpp`
   - `gen_subseq.py`
   - Updated `RoadMap.md` to include a hyperlink to this folder and checked the relevant box.

### Checklist
- [x] Added code in Java, C++, and Python.
- [x] Updated `RoadMap.md` with a checkbox and hyperlink.
- [x] Verified all files compile/run without errors.
- [x] Added meaningful comments and test cases in the code.

### CODE REVIEW

**Comment by imsuraj675** [comment]
Make these modifications: 
- Don't create a function of void type. The function should return the required thing. In coding, when we call a function we expect it to return some value, instead of printing it on console. So, return a list of strings. 
- The specified time complexity is O(2^n), means that all subsequences should be generated.
- Make sure to update the RoadMap.md too, before raising a pull request.

**Comment by ittou-shura** [comment]
Ok!

**Comment by ittou-shura** [comment]
Resubmitted PR with modified algo for generating all subsequences instead of substrings
Also modified the checklist in RoadMap.md

**Comment by imsuraj675** [comment]
Make these modifications:
- You have some merge conflicts. First resolve all the conflicts. Pull the latest data from the repo by executing the command **git pull**. 
- The python code is not same as cpp and java code. Implement all in same manner, and instead of using string, use mutable types to increase efficiency (list for python, string builder for java).

**Comment by ittou-shura** [comment]
ok on it

**Pull request closed without merging**
